configuration: 
  projectName: configclient
server:
  port: 8000
message:
  greeting: Hello-demo444 from the configuration!
assure:
  hostname: "https://sigapp.signicat.net:4443"
  path: "/std/method"
  service: "nbidmobile"
  profile: "New-signicat-profile"
